/** @type {import('next').NextConfig} */
import shopifyRedirects from "./lib/redirects.json" with { type: "json" };

const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    // 301s from old Shopify URLs → new slugs (generated by
    // scripts/generate-redirects.mjs). Preserves SEO at domain cutover.
    return shopifyRedirects;
  },
  images: {
    // Supabase Storage + POD CDNs (images come from migration, Session 03).
    remotePatterns: [
      { protocol: "https", hostname: "*.supabase.co", pathname: "/storage/v1/object/public/**" },
      { protocol: "https", hostname: "files.cdn.printful.com" },
      { protocol: "https", hostname: "images-api.printify.com" },
      { protocol: "https", hostname: "cdn.shopify.com" },
    ],
  },
};

export default nextConfig;

// Enables Cloudflare bindings (env, R2, etc.) during `next dev`.
// Safe no-op when the OpenNext Cloudflare context is unavailable.
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";
initOpenNextCloudflareForDev();
