/** @type {import('next').NextConfig} */
import shopifyRedirects from "./lib/redirects.json" with { type: "json" };

const nextConfig = {
  reactStrictMode: true,
  // PUBLIC, browser-safe config baked in at build so the Cloudflare Workers
  // build doesn't depend on dashboard build-time env vars. All of these are
  // public by design — the Supabase anon key and Stripe publishable key ship to
  // every browser anyway (the anon key is gated by RLS). A real env var of the
  // same name overrides the fallback (e.g. the real domain at cutover).
  // SECRET keys (service role, Stripe secret, Resend, POD) are NOT here — they
  // stay in the worker's runtime env.
  env: {
    NEXT_PUBLIC_SUPABASE_URL:
      process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://pajkxzoloxytwqzxvabu.supabase.co",
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhamt4em9sb3h5dHdxenh2YWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5MDUzMTYsImV4cCI6MjA5NTQ4MTMxNn0.hN7KoPbh-pWXMnMOnQkCuSwjLgg-dSOS5xsGv6IZ4is",
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY ??
      "pk_test_51Tbpa8J9KizllqPH12T4T1FYkGLXgV2Prx0vYWU3fBns7H5iJHQcUxhlCQ06GQ1jMl3qZxH1cG36upmVJcI4IfD100o5hzuE4X",
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? "https://nauticalnomads.com",
    NEXT_PUBLIC_ALLOW_INDEXING: process.env.NEXT_PUBLIC_ALLOW_INDEXING ?? "false",
  },
  async redirects() {
    // 301s from old Shopify URLs → new slugs (generated by
    // scripts/generate-redirects.mjs). Preserves SEO at domain cutover.
    return shopifyRedirects;
  },
  images: {
    // Supabase Storage + POD CDNs (images come from migration, Session 03).
    remotePatterns: [
      { protocol: "https", hostname: "*.supabase.co", pathname: "/storage/v1/object/public/**" },
      { protocol: "https", hostname: "files.cdn.printful.com" },
      { protocol: "https", hostname: "images-api.printify.com" },
      { protocol: "https", hostname: "cdn.shopify.com" },
    ],
  },
};

export default nextConfig;

// Enables Cloudflare bindings (env, R2, etc.) during `next dev`.
// Safe no-op when the OpenNext Cloudflare context is unavailable.
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";
initOpenNextCloudflareForDev();
